
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

tts:
  - platform: google_translate
    language: "nl"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  packages: !include_dir_named packages
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.68.0/24
        - 127.0.0.1
    - type: homeassistant

lovelace:
  mode: yaml

#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: homeassistant
#  password: "!Adp56gyd"
#  max_retries: 3
#  default_measurement: state