custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

background: 'https://github.com/basnijholt/lovelace-ios-dark-mode-theme/blob/master/backgrounds/homekit-bg-4.jpeg'

resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module

title: Home
views:
  - !include /config/lovelace/00_overzicht.yaml
  - !include /config/lovelace/01_licht.yaml
  - !include /config/lovelace/02_temperaturen.yaml
  - !include /config/lovelace/03_media-spelers.yaml
  - !include /config/lovelace/04_afval.yaml
  - !include /config/lovelace/05_camera.yaml
  - !include /config/lovelace/06_mobiele-apparaten.yaml
  - !include /config/lovelace/08_automatiseringen.yaml
  - !include /config/lovelace/99_test.yaml
