homeassistant:

# https://github.com/snarky-snark/home-assistant-variables
var:
  msg_count:
    initial_value: 2
    friendly_name: "Message count"
    
  msg_block:
    initial_value: "false"
    friendly_name: "block automation for specific time"
    
### sensor.trash_tomorrow (trash_today) geeft de waardes: geen, gft-afval,...
sensor:
  - platform: afvalwijzer
    provider: afvalstoffendienstkalender
    zipcode: !secret postcode
    housenumber: !secret huisnummer

automation:
  #####################################
  ### TTS Afval vandaag buitenzetten ###
  #####################################
  - alias: Afval - melding morgen buitenzetten
    trigger:
      platform: state
      entity_id: binary_sensor.woonkamer_sensor_motion
      to: "on"
    condition:
      - condition: state
        entity_id: person.rogier_van_turnhout
        state: "home"
      - condition: time
        after: "7:15:00"
        before: "12:00:00"
      - condition: template
        value_template: '{{ states("sensor.trash_today") != "Geen" }}'
      - condition: numeric_state
        entity_id: var.msg_count
        above: 0
      - condition: state
        entity_id: var.msg_block
        state: "false"
    action:
      - service: tts.google_translate_say
        entity_id: media_player.huiskamer
        data_template:
          message: >-
            Rogier, vandaag {{ states("sensor.trash_today") }} aan straat zetten.
      - service: var.set
        data:
          entity_id: var.msg_count
          value_template: "{{ (states('var.msg_count') | int) - 1 }}"
      - service: var.set
        data:
          entity_id: var.msg_block
          value: "true"
          
  ######################################
  ### TTS Papier Afval morgen buitenzetten ###
  ######################################
  - alias: Afval - melding morgen papier buitenzetten
    trigger:
      platform: state
      entity_id: binary_sensor.woonkamer_sensor_motion
      to: "on"
    condition:
      - condition: state
        entity_id: person.rogier_van_turnhout
        state: "home"
      - condition: time
        after: "07:00:00"
        before: "09:00:00"
      - condition: template
        value_template: '{{ states("sensor.trash_tomorrow") == "Papier" }}'
      - condition: numeric_state
        entity_id: var.msg_count
        above: 0
      - condition: state
        entity_id: var.msg_block
        state: "false"
    action:
      - service: tts.google_translate_say
        entity_id: media_player.huiskamer
        data_template:
          message: >-
            Rogier. Morgen papier aan straat zetten.
      - service: var.set
        data:
          entity_id: var.msg_count
          value_template: "{{ (states('var.msg_count') | int) - 1 }}"
      - service: var.set
        data:
          entity_id: var.msg_block
          value: "true"
          
  #################################
  ### blokkeer automation reset ###
  #################################
  - alias: afval - blokkeer melding voor een specifieke tijd
    trigger:
      - platform: state
        entity_id: var.msg_block
        to: "true"
        for:
          minutes: 30
      - platform: homeassistant
        event: start
    action:
      - service: var.set
        data:
          entity_id: var.msg_block
          value: "false"

  #######################
  ### reset msg_count ###
  #######################
  - alias: Afval - reset vaiabele msg_count
    trigger:
      - platform: time
        at: "04:00:00"
    action:
      - service: var.set
        data:
          entity_id: var.msg_count
          value: 2