homeassistant:

input_boolean:
  bedtime:
    name: Bedtijd
    initial: off
    icon: mdi:sleep

automation:
  - alias: Bedtijd - direct
    trigger:
      platform: state
      entity_id: input_boolean.bedtime
      to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.lamp_in_slaapkamer
          brightness: 1
      - service: switch.turn_off
        entity_id: switch.desktop_computer
      - service: climate.set_preset_mode
        data:
          entity_id: climate.toon_thermostat
          preset_mode: "sleep"
  
  - alias: Bedtijd - na 3 minuten
    trigger:
      platform: state
      entity_id: input_boolean.bedtime
      to: "on"
      for:
        minutes: 3
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bedtime
      # Lichten 
      - service: light.turn_off
        entity_id: light.binnenverlichting
