homeassistant:

sensor:
  - platform: template
    sensors:
      media_spelers:
        friendly_name: Media Spelers
        value_template: "{{ states.media_player | count }}" 
      device_trackers:
        friendly_name: Device Trackers
        value_template: "{{ states.device_tracker | count }}"
      lampen:
        friendly_name: Lampen
        value_template: "{{ (states.light | count) - 7 }}" # -7 groepen
      automatisering:
        friendly_name: Automatiseringen
        value_template: "{{ states.automation | count }}"
      sensoren:
        friendly_name: Sensoren
        value_template: "{{ states.sensor | count }}"
      binary_sensors:
        friendly_name: Binary_sensors
        value_template: "{{ states.binary_sensor | count }}"
      covers:
        friendly_name: Covers
        value_template: "{{ states.cover | count }}"
      input_booleans:
        friendly_name: Input_booleans
        value_template: "{{ states.input_boolean | count }}"
      input_selects:
        friendly_name: Input Selects
        value_template: "{{ states.input_select | count }}"