homeassistant:

cover:
  - platform: group
    name: Gordijnen
    entities:
      - cover.gordijn_links
      - cover.gordijn_rechts

### Gordijnen sluiten - start ###
automation:
  - alias: "gordijnen - sluit gordijnen bij zonsondergang"
    trigger:
      platform: sun
      event: sunset
    action:
      service: cover.close_cover
      entity_id: cover.gordijnen
### Gordijnen sluiten - eind ###


### Gordijnen open - start ###
  - alias: "gordijnen - open gordijnen bij zonsopkomst (en niemand thuis)"
    trigger:
      platform: sun
      event: sunrise
    condition:
      condition: state
      entity_id: group.people
      state: "not_home"
    action:
      service: cover.open_cover
      entity_id: group.gordijnen

  - alias: "gordijnen - open gordijnen bij verlaten woning (en zon is op)"
    trigger:
      platform: state
      entity_id: group.people
      to: "not_home"
    condition:
      condition: state
      entity_id: sun.sun
      state: "above_horizon"
    action:
      service: cover.open_cover
      entity_id: group.gordijnen
### Gordijnen sluiten - eind ###