homeassistant:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# Router gegevens
upnp:
  port_mapping: true
  ports:
    hass: 8000
    8080: 8080