## https://www.home-assistant.io/components/recorder/
## https://www.home-assistant.io/components/history/
## https://www.home-assistant.io/integrations/logbook/

homeassistant:

recorder:
  purge_keep_days: 7
  purge_interval: 7
  exclude:
    domains:

    entities:
      - sensor.trash_firstdate
      - sensor.trash_firstwastetype
      - sensor.trash_gft_afval
      - sensor.trash_next
      - sensor.trash_papier
      - sensor.trash_today
      - sensor.trash_tomorrow
      - sensor.time
      - sensor.time_date

logbook:
  exclude:
    domains:
      - light
      - media_player
    entities:
      - binary_sensor.woonkamer_sensor_motion
      - binary_sensor.kitchen_motion_motion
      - binary_sensor.bathroom_motion_motion
      - binary_sensor.bijkeuken_motion_motion
      - binary_sensor.toilet_motion_motion
      - binary_sensor.corridor_motion_motion
      - binary_sensor.entrance_motion_motion
      - binary_sensor.werkdag
      - binary_sensor.werkdag_morgen
      - sensor.time
      - sensor.time_date      
history:
#  exclude:
#    domains:
#     - device_tracker
#     - media_player
#     - binary_sensor
#     - automation
#     - light
#     - sensor
#     - climate
