homeassistant:

sensor:
  - platform: version
  
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: ipv4_address
        arg: enp0s18
      - type: processor_use
      - type: last_boot
      - type: network_in
        arg: enp0s18
      - type: network_out
        arg: enp0s18
      - type: throughput_network_in
        arg: enp0s18
      - type: throughput_network_out
        arg: enp0s18

## Proxmox VE
proxmoxve:
  - host: !secret proxmox_host
    username: !secret proxmox_user
    password: !secret proxmox_pass
    verify_ssl: false
    nodes:
      - node: "pve"
        vms:
          - 100
          - 101
        containers:
          - 102