homeassistant:

automation:
- alias: "thema - selecteer licht thema"
  trigger:
    - platform: sun
      event: sunrise
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - service: frontend.set_theme
      data:
        name: clear

- alias: "thema - selecteer donker thema"
  trigger:
    - platform: sun
      event: sunset
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: frontend.set_theme
      data:
        name: dark