homeassistant:

### Lichtgroepen ###
light:
  - platform: group
    name: Hue Plays
    entities:
      - light.hue_play_1
      - light.hue_play_2
      
  - platform: group
    name: Computerverlichting
    entities:
      - light.computerlamp
      - light.hue_plays

automation:
  ### Verlichting achter monitoren en computerlamp aan ###
  - alias: "verlichting - Computerverlichting aan als computer aan is"
    trigger:
      - platform: state
        entity_id: switch.desktop_computer
        to: "on"
    action:
      - service: scene.turn_on
        entity_id: scene.normaal
        
  ### verander hue plays van kleur na 11 uur
  - alias: "verlichting - Verander kleur om 23:00 uur"
    trigger:
      - platform: time
        at: "23:00:00"
    condition:
      condition: state
      entity_id: switch.desktop_computer
      state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.na_11_uur

  ### verander hue plays van kleur na 00:00 uur
  - alias: "verlichting - Verander kleur om 00:00 uur"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      condition: state
      entity_id: switch.desktop_computer
      state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.na_00_uur

  ### Verlichting achter monitoren en computerlamp uit ###
  - alias: "verlichting - Computerverlichting uit als computer aan is"
    trigger:
      - platform: state
        entity_id: switch.desktop_computer
        to: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: 
            - light.hue_plays
            - light.computerlamp