homeassistant:

automation:
  ############################
  ### Bijkeukenverlichting ###
  ############################
  - alias: "verlichting - bijkeukenverlichting aan bij beweging"
    trigger:
      - platform: state
        entity_id: binary_sensor.bijkeuken_motion_motion
        to : "on"
    condition:
      - condition: numeric_state
        entity_id: sensor.bijkeuken_motion_light_level
        below: 6
    action:
      - service: light.turn_on
        entity_id: light.bijkeuken_lamp

  - alias: "verlichting - Bijkeukenverlichting uit bij 5 minuten geen beweging"
    trigger:
      - platform: state
        entity_id: binary_sensor.bijkeuken_motion_motion
        to : "off"
        for:
          minutes: 5
    action:
      - service: light.turn_off
        entity_id: light.bijkeuken_lamp