homeassistant:

### Lichtgroepen ###
light:
  - platform: group
    name: Hue Plays
    entities:
      - light.hue_play_1
      - light.hue_play_2
      
  - platform: group
    name: Computerverlichting
    entities:
      - light.computerlamp
      - light.hue_plays

scene:
  - name: "normaal"
    entities:
      light.hue_plays:
        state: on
        brightness: 255
        rgb_color: [ 191, 29, 255 ] # purple
      light.computerlamp: on
  - name: "na 11 uur"
    entities:
      light.hue_plays:
        state: on
        brightness: 255
        rgb_color: [ 255, 190, 44 ] # orange
      light.computerlamp: on
  - name: "na 00 uur"
    entities:
      light.hue_plays:
        state: on
        brightness: 255
        rgb_color: [ 255, 0, 0 ] # red
      light.computerlamp: on 

automation:
  ### Verlichting achter monitoren en computerlamp aan ###
  - alias: "verlichting - Computerverlichting aan als computer aan is"
    trigger:
      - platform: state
        entity_id: switch.desktop_computer
        to: "on"
    action:
      - service: scene.turn_on
        entity_id: scene.normaal
        
  ### verander hue plays van kleur na 11 uur
  - alias: "verlichting - Verander kleur om 23:00 uur"
    trigger:
      - platform: time
        at: "23:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.na_11_uur

  ### verander hue plays van kleur na 00:00 uur
  - alias: "verlichting - Verander kleur om 00:00 uur"
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.na_00_uur

  ### Verlichting achter monitoren en computerlamp uit ###
  - alias: "verlichting - Computerverlichting uit als computer aan is"
    trigger:
      - platform: state
        entity_id: switch.desktop_computer
        to: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: 
            - light.hue_plays
            - light.computerlamp