homeassistant:

#############
### setup ###
#############
hue:
  bridges:
    - host: 192.168.68.132
      allow_unreachable: true
      allow_hue_groups: false

############
### Flux ###
############
switch:
  - platform: flux
    lights:
      - light.salontafel_lamp
    name: Flux salontafellamp
#    start_time: '7:00'
#    stop_time: '0:00'
#    start_colortemp: 4500
#    sunset_colortemp: 2000
#    stop_colortemp: 1900
    mode: mired
  - platform: flux
    lights:
      - light.staande_lamp_1
      - light.staande_lamp_2
      - light.staande_lamp_3
      - light.staande_lamp_4
      - light.staande_lamp_5
      - light.staande_lamp_6
    name: Flux staandelamp
    mode: mired

### Lichtgroepen ###
light:
  - platform: switch
    name: Kerstboom
    entity_id: switch.kerstboom

  - platform: group
    name: Hue Blooms
    entities:
      - light.bloem_1
      - light.bloem_2

  - platform: group
    name: Staande lamp
    entities:
      - light.staande_lamp_1
      - light.staande_lamp_2
      - light.staande_lamp_3
      - light.staande_lamp_4
      - light.staande_lamp_5
      - light.staande_lamp_6

  - platform: group
    name: Afzuigkap
    entities:
      - light.afzuigkap_1
      - light.afzuigkap_2 

  - platform: group
    name: Binnenverlichting
    entities:
      - light.achterkamerlamp
      - light.badkamer
      - light.badkamer_spiegel
      - light.bijkeuken_lamp
      - light.hue_blooms
      - light.computerlamp
      - light.hal
      - light.hue_plays
      - light.keuken
      - light.lamp_in_slaapkamer
      - light.overloop
      - light.sam
      - light.storm
      - light.toilet
      - light.salontafel_lamp
      - light.staande_lamp
      - light.kerstboom
      - light.afzuigkap

automation:
  ###############################################
  ### Flux aanzetten bij start Home Assistant ###
  ###############################################
  - alias: "verlichting - flux aan bij start"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: switch.turn_on
        entity_id: switch.flux_salontafel_lamp
      - service: switch.turn_on
        entity_id: switch.flux_staande_lamp

  
  #######################################################    
  ### Alle verlichting uit bij langdurige afwezigheid ###
  #######################################################
  - alias: "verlichting - verlichting uit bij langdurige afwezigheid"
    trigger:
      platform: state
      entity_id: group.people
      to: "not_home"
      for:
        minutes: 10
    condition:
      condition: state
      entity_id: light.binnenverlichting
      state: "on"
    action:
      - service: light.turn_off
        entity_id: light.binnenverlichting
      
  ###########################################
  ### Woonkamerverlichting bij thuiskomst ###
  ###########################################
  - alias: "verlichting - woonkamerverlichting aan bij thuiskomst"
    trigger: 
      - platform: state
        entity_id: group.people
        to: "home"
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.bloem_1
            - light.bloem_2
            - light.staande_lamp

  ######################################################
  ### Woonkamerverlichting wanneer mensen thuis zijn ###
  ######################################################
  - alias: "verlichting - woonkamerverlichting aan bij zonsondergang"
    trigger: 
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: group.people
        state: "home"
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.bloem_1
            - light.bloem_2
            - light.staande_lamp

  ########################################
  ## salontafellamp aan bij thuiskomst ##
  ########################################
  - alias: "verlichting - Salontafellamp aan bij thuiskomst"
    trigger: 
      - platform: state
        entity_id: group.people
        to: "home"
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: template
        value_template: '{{ states("media_player.huiskamer_tv") == "off" }}'
    action:
      - service: light.turn_on
        entity_id:
          - light.salontafel_lamp

  ###########################################
  ## salontafel lamp aan bij zonsondergang ##
  ###########################################
  - alias: "verlichting - salontafellamp aan bij zonsondergang"
    trigger: 
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: group.people
        state: "home"
      - condition: template
        value_template: '{{ states("media_player.huiskamer_tv") == "off" }}'
    action:
      - service: light.turn_on
        entity_id:
          - light.salontafel_lamp

  #######################################
  ### salontafellamp uit bij tv kijken ###
  #######################################
  - alias: "verlichting - woonkamerlamp uit wanneer tv wordt gekeken"
    trigger:
      - platform: template
        value_template: '{{ states("media_player.huiskamer_tv") != "off" }}'
    condition: 
      - condition: state
        entity_id: light.salontafel_lamp
        state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: light.salontafel_lamp
          transition: 10